Controllers/FitnessController.cs
using Microsoft.AspNetCore.Mvc;

namespace FitnessSite.Controllers
{
    public class FitnessController : Controller
    {
        public IActionResult VreauSaSlabesc()
        {
            return View();
        }

        public IActionResult VreauMasaMusculara()
        {
            return View();
        }

        public IActionResult VreauPlanAlimentar()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ro">
<head>
    <link rel="icon" type="image/jpg" href="~/images/MuscleIcon.jpg">

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Remodeleaza-ti corpul</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEBSITE.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="nav-link" href="@Url.Action("Index", "Home")"> Fitness </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("VreauSaSlabesc", "Fitness")">Slabire</a>
                          
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("VreauMasaMusculara", "Fitness")">Masa Musculara</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("VreauPlanAlimentar", "Fitness")">Plan Alimentar</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("DespreMine", "Home")"> Despre mine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Contact", "Home")"> Contact </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center py-3">
        <div class="container">
            <a> Antrenor acreditat FRCF </a>
           <a class="nav-link" href="@Url.Action("Index", "Home")">  2025 - Site Fitness 
           <a asp-area="" asp-controller="Home" class="nav-link" href="@Url.Action("Contact", "Home")"> Contact </>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>